### PR TITLE
minor typo

### PR DESCRIPTION
**Pull request by JdenHartog**
Because all these pull request and issues might have a rather negative ‘vibe’, I’d like to add a positive note: I'm very happy, amazed, satisfied and even a bit jealous of the OpenSesame project and the excellent documentation!

**Happy Holidays!**

### CODE REVIEW

**Comment by smathot** [comment]
Thank you! And I don't see issues as negative at all--I think they're a constructive contribution! :santa:

**Comment by smathot** [comment]
That being said, this pull request seems to be empty--there is no diff. Which is odd, because you generally cannot even submit empty changes through git. In any case, I assume that you wanted to add the missing 'overview' in 'provides an of '?

**Comment by JdenHartog** [comment]
Wanted to delete the word 'how' in **The variable inspector** (see iamge below).
capture

**Comment by smathot** [comment]
Indeed!

**Pull request merged**
